<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE template [
  <!ELEMENT template (section)+>
  <!ELEMENT section (header,(paragraph|section|table|plot)+)>
  <!ELEMENT paragraph (#PCDATA | var)*>
  <!ELEMENT header (#PCDATA)>
  <!ELEMENT table (#PCDATA)>
  <!ELEMENT plot (#PCDATA)>
  <!ELEMENT var EMPTY>
  <!ATTLIST var   ref  CDATA #REQUIRED>
  <!ATTLIST table ref CDATA #REQUIRED>
  <!ATTLIST plot ref CDATA #REQUIRED>
]>

<template>
  <section>
    <header>Vollzähligkeit</header>
    <paragraph>Im Zeitraum <pref ref="zeitraum"/> wurden in der Notaufnahme insgesamt <pref ref="anzahl"/> Patienten behandelt.</paragraph>
    <paragraph>Die folgenden Tabellen stellen dar, wie vollständig die Angaben in diesem Zeitraum waren. Jede explizit Angabe (auch "Nein" oder ähnliches in einer Auswahl) wird gezählt. Als fehlend zählen nur Angaben, die leer sind. Natürlich ist dies in vielen Fällen auch kein Hinweis auf mangelnde Datenqualität. Falls allerdings wichtige Angaben, die eigentlich routinemäßig erhoben werden sollten, viel zu selten auftauchen, könnte dies ein Hinweis auf Probleme beim Daten-Import sein.</paragraph>
    <section>
      <header>Daten auf der Ebene Patientenkontakt</header>
      <table ref="t1.1">Tabelle 1.1: Vollzähligkeit der Datenelemente</table>
    </section>
    <section>
      <header>Abschlussdiagnosen</header>
      <paragraph>Die Abschlussdiagnosen können pro Fall mehrfach vorkommen. Eine führende Diagnose sollte immer vorhanden sein, daher müssten die ersten beiden Werte der Tabelle gleich sein. Falls bei den Diagnose-Zusätzen zu wenig angezeigt wird, obwohl dies routinemäßig erhoben wird, könnte das ein Hinweis auf Probleme beim Daten-Import sein.</paragraph>
      <table ref="t1.2">Tabelle 1.2: Vollzähligkeit der Diagnosen</table>
    </section>
  </section>
</template>
