<?xml version="1.0"?>
<!DOCTYPE template [
  <!ELEMENT template (section)+>
  <!ELEMENT section (header,(paragraph|section|table|plot)+)>
  <!ELEMENT paragraph (#PCDATA | var)*>
  <!ELEMENT header (#PCDATA)>
  <!ELEMENT table (#PCDATA)>
  <!ELEMENT plot (#PCDATA)>
  <!ELEMENT var EMPTY>
  <!ATTLIST var   ref  CDATA #REQUIRED>
  <!ATTLIST table ref CDATA #REQUIRED>
  <!ATTLIST plot ref CDATA #REQUIRED>
]>

<template>
  <section>
    <header>1 Fallzahlen</header>
    <paragraph>Einleitungstext <var ref="anzahl"/> Fallzahlen</paragraph>
    <section>
      <header>1.1 Fallzahlen nach Wochentag und Aufnahmezeit</header>
      <plot ref="p1">Grafik 1: Fallzahlen nach Wochentag und Aufnahmezeit</plot>
      <table ref="t1">Tabelle 1: Fallzahlen nach Wochentag und Aufnahmezeit</table>
    </section>
    <section>
      <header>1.2 Fallzahlen nach Zuweisung</header>
      <plot ref="p2">Grafik 2: Fallzahlen nach Zuweisung</plot>
      <table ref="t2">Tabelle 2: Fallzahlen nach Zuweisung</table>
    </section>
    <section>
      <header>1.3 Fallzahlen nach Transportmittel</header>
      <plot ref="p3">Grafik 3: Fallzahlen nach Transportmittel</plot>
      <table ref="t3">Tabelle 3: Fallzahlen nach Transportmittel</table>
    </section>
     <section>
      <header>1.4 Fallzahlen nach Einweisungsart</header>
      <plot ref="p4">Grafik 4: Fallzahlen nach Einweisungsart</plot>
      <table ref="t4">Tabelle 4: Fallzahlen nach Einweisungsart</table>
    </section>
     <section>
      <header>1.5 Altersverteilung der Patienten nach Geschlecht</header>
      <plot ref="p5">Grafik 5: Altersverteilung der Patienten nach Geschlecht</plot>
      <table ref="t5">Tabelle 5: Altersverteilung der Patienten nach Geschlecht</table>
    </section>
     <section>
      <header>1.6 Fallzahlen nach Dringlichkeit (MTS)</header>
      <plot ref="p6">Grafik 6: Fallzahlen nach Dringlichkeit (MTS)</plot>
      <table ref="t6">Tabelle 6: Fallzahlen nach Dringlichkeit (MTS)</table>
    </section>
    <section>
      <header>1.7 Verlegung/Entlassung</header>
      <plot ref="p7">Grafik 7: Verlegung/Entlassung</plot>
      <table ref="t7">Tabelle 7: Verlegung/Entlassung</table>
    </section>
     <section>
      <header>1.8 isolierte Patienten</header>
      <plot ref="p8">Grafik 8: isolierte Patienten</plot>
      <table ref="t8">Tabelle 8: isolierte Patienten</table>
    </section>
     <section>
      <header>1.9 Infektionssurveillance</header>
      <plot ref="p9">Grafik 9: Infektionssurveillance</plot>
      <table ref="t9" width="40%">Tabelle 9: Infektionssurveillance</table>
    </section>
  </section>
  <section>
    <header>2 Prozesszeiten</header>
    <paragraph>Einleitungstext Prozesszeiten <var ref="bereich"/></paragraph>
    <plot ref="pa">Grafik 10: Prozesszeiten</plot>
    <table ref="t10">Tabelle 10: Prozesszeiten</table>
    <section>
    <header>2.1 Prozesszeiten nach Ersteinschaetzung</header>
    <plot ref="p11">Grafik 11: Prozesszeiten nach Ersteinschaetzung</plot>
    <table ref="t11">Tabelle 11: Prozesszeiten nach Ersteinschaetzung</table>
  </section>
  </section>
  <section>
    <header>3 Vitalparameter und Scores</header>
    <paragraph>Einleitungstext Vitalparameter und Scores</paragraph>
    <plot ref="pa">Grafik 12: Vitalparameter und Scores</plot>
    <table ref="ta">Tabelle 12: Vitalparameter und Scores</table>
  </section>
  <section>
    <header>4 Diagnosen</header>
    <paragraph>Einleitungstext Diagnosen</paragraph>
    <section>
      <header>4.1 Top 10 Diagnosen</header>
      <plot ref="p13">Grafik 13: Top 10 Diagnosen</plot>
      <table ref="t13">Tabelle 13: Top 10 Diagnosen</table>
    </section>
    <section>
      <header>4.2 Top 10 CEDIS</header>
      <plot ref="p14">Grafik 14: Top 10 CEDIS</plot>
      <table ref="t14">Tabelle 14: Top 10 CEDIS</table>
    </section>
  </section>
   <section>
  <header>5 Diagnostik</header>
    <paragraph>Einleitungstext Diagnostik</paragraph>
    <plot ref="pa">Grafik 15: Diagnostik</plot>
    <table ref="ta">Tabelle 15: Diagnostik</table>
  </section>
</template>
